name: Metrics
on:
  schedule:
    - cron: "*/10 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Default metrics
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.base.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: header, activity, community, repositories, metadata
      
        - name: Anilist - Favorites characters
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.anilist.characters.svg
            token: NOT_NEEDED
            base: ""
            plugin_anilist: yes
            plugin_anilist_sections: favorites, characters
            plugin_anilist_limit_characters: 22


        - name: Youtube Music - Recently listed
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.youtubemusic.svg
            token: NOT_NEEDED
            base: ""
            plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKEN }}
            plugin_music: yes
            plugin_music_mode: recent
            plugin_music_provider: youtube

        - name: Last.fm  - Recently listed
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.lastfm.svg
            token: NOT_NEEDED
            base: ""
            plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
            plugin_music: yes
            plugin_music_provider: lastfm
            plugin_music_user: xxspell

        - name: Indepth analysis
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.languages.indepth.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_languages: yes
            plugin_languages_ignored: >-
              html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
              gnuplot
            plugin_languages_indepth: yes
            plugin_languages_details: lines, bytes-size
            plugin_languages_limit: 4
            plugin_languages_analysis_timeout: 15


        - name: Compact display
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.achievements.compact.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_achievements: yes
            plugin_achievements_only: >-
              polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
              scripter, packager, explorer, infographile, manager
            plugin_achievements_display: compact
            plugin_achievements_threshold: X


        - name: WakaTime
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.wakatime.svg
            token: NOT_NEEDED
            base: ""
            plugin_wakatime: yes
            plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
            plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
            plugin_wakatime_url: ${{ secrets.WAKATIME_API_BASE_URL }}











