name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "*/10 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      
        - name: Anilist - Favorites characters
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.anilist.characters.svg
            token: NOT_NEEDED
            base: ""
            plugin_anilist: yes
            plugin_anilist_sections: characters
            plugin_anilist_limit_characters: 22

        - name: Youtube Music - Recently listed
          uses: lowlighter/metrics@latest
          with:
            token: NOT_NEEDED
            base: ""
            plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKEN }}
            plugin_music: yes
            plugin_music_mode: recent
            plugin_music_provider: youtube

        - name: Last.fm  - Recently listed
          uses: lowlighter/metrics@latest
          with:
            token: NOT_NEEDED
            base: ""
            plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
            plugin_music: yes
            plugin_music_provider: lastfm
            plugin_music_user: RJ











