name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Default metrics
          uses: frieren-mage/metrics@master
          with:
            filename: metrics.base.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: header, activity, community, repositories

        - name: Display
          uses: frieren-mage/metrics@master
          with:
            filename: metrics.plugin.achievements.compact.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_achievements: yes
            plugin_achievements_only: >-
              polyglot, stargazer, deployer, member, maintainer, developer,
              scripter
            plugin_achievements_display: detailed
            plugin_achievements_threshold: X
