name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Default metrics
          uses: frieren-mage/metrics@master
          with:
            filename: metrics.base.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: header, activity, community, repositories

        - name: In-depth Language Analysis
          uses: frieren-mage/metrics@master
          with:
            # Output configuration
            filename: metrics.plugin.languages.indepth.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            
            # Repository settings
            plugin_languages_categories: all    # Include all repository categories
            plugin_languages_analysis_timeout_repositories: 120  # Increased timeout for multiple repos
            plugin_languages_repositories: "*"   # Analyze all repositories
            plugin_languages_repositories_batch: 10  # Process 10 repositories at a time
            
            # Language analysis settings
            plugin_languages: true
            plugin_languages_indepth: true
            plugin_languages_commits: true
            plugin_languages_commits_history: true
            
            # Analysis details
            plugin_languages_details: >-
              lines,
              bytes-size,
              commits
            
            # Limits and timeouts
            plugin_languages_limit: 4
            plugin_languages_analysis_timeout: 15
            
            # Excluded languages
            plugin_languages_ignored: >-
              html,
              css,
              less,
              qmake,
              lex,
              cmake,
              shell,
              gnuplot


        - name: Display
          uses: frieren-mage/metrics@master
          with:
            filename: metrics.plugin.achievements.compact.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_achievements: yes
            plugin_achievements_only: >-
              polyglot, stargazer, deployer, member, maintainer, developer,
              scripter
            plugin_achievements_display: detailed
            plugin_achievements_threshold: X
