name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "*/10 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
      
        - name: Anilist - Favorites characters
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.anilist.characters.svg
            token: NOT_NEEDED
            base: ""
            plugin_anilist: yes
            plugin_anilist_sections: characters
            plugin_anilist_limit_characters: 22

        - name: Youtube Music - Recently listed
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.youtubemusic.svg
            token: NOT_NEEDED
            base: ""
            plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKEN }}
            plugin_music: yes
            plugin_music_mode: recent
            plugin_music_provider: youtube

        - name: Last.fm  - Recently listed
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.lastfm.svg
            token: NOT_NEEDED
            base: ""
            plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
            plugin_music: yes
            plugin_music_provider: lastfm
            plugin_music_user: xxspell

        - name: Indepth analysis
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.languages.indepth.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_languages: yes
            plugin_languages_ignored: >-
              html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
              gnuplot
            plugin_languages_indepth: yes
            plugin_languages_details: lines, bytes-size
            plugin_languages_limit: 4
            plugin_languages_analysis_timeout: 15











