name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Default metrics
          uses: frieren-mage/metrics@master
          with:
            filename: metrics.base.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: header, activity, community, repositories

        - name: In-depth Language Analysis
          uses: frieren-mage/metrics@master
          with:
            # Output configuration
            filename: metrics.plugin.languages.indepth.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            
            # Repository settings
            repositories: "*"              # All repositories
            repositories_batch: 10         # Process in batches
            #repositories_forks: true       # Include forks
            repositories_affiliations: owner, collaborator, organization_member
            plugin_languages_analysis_timeout_repositories: 240  # Increased timeout further
            
            # Language analysis settings
            plugin_languages: true
            plugin_languages_indepth: true
            plugin_languages_recent_categories: all
            plugin_languages_recent_days: 0    # No time limit
            plugin_languages_recent_load: 1000  # Load more commits
            plugin_languages_sections: most-used, recently-used
            
            # Commit analysis
            plugin_languages_commits: true
            plugin_languages_commits_history: true
            plugin_languages_commits_load: 1000  # Load more historical commits
            plugin_languages_commits_recent_days: 0  # No time limit
            
            # Analysis details
            plugin_languages_details: >-
              lines,
              bytes-size,
              commits,
              history
            
            # Limits and timeouts
            plugin_languages_limit: 4
            plugin_languages_threshold: 0%      # Include all languages
            plugin_languages_analysis_timeout: 30  # Increased per-repo timeout
            
            # Excluded languages
            plugin_languages_ignored: >-
              html,
              css,
              less,
              qmake,
              lex,
              cmake,
              shell,
              gnuplot
    

        - name: Display
          uses: frieren-mage/metrics@master
          with:
            filename: metrics.plugin.achievements.compact.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_achievements: yes
            plugin_achievements_only: >-
              polyglot, stargazer, deployer, member, maintainer, developer,
              scripter
            plugin_achievements_display: detailed
            plugin_achievements_threshold: X
